name: analytics_env
channels:
  - defaults
dependencies:
  - pip=20.2.2
  - python=3.8.5
  - pip:
      - apiclient==1.0.4
      - black==20.8b1
      - google-api-python-client==1.12.8
      - numpy==1.19.5
      - oauth2client==4.1.3
      - pandas==1.2.0
      - pylint==2.6.0
      - requests==2.24.0
      - scikit-learn==0.24.0
      - tensorflow==2.4.0